"""Turn web/ into include/web_assets.h, gzipped, at build time.

Why the page is compiled in rather than put on a filesystem: nothing mounts
LittleFS any more (main.cpp says why), and the rig is updated over the air --
one image to flash is one thing that can go wrong, where an image plus a
filesystem is two, and the two can disagree about which version they are.

Why it is one file: the front end is served by a synchronous HTTP server, so
three assets would be three requests answered one after another. The CSS and JS
are authored separately and inlined here, which keeps web/index.html openable
in a desktop browser for layout work while the device still serves a single
document.

Why gzip: the page is around 40 kB of text and compresses to roughly a
quarter of that. Every browser has accepted gzip for twenty years, and the
saving is flash the firmware would otherwise not have.
"""

import gzip
import io
import os
import re

Import("env")  # noqa: F821 -- injected by PlatformIO

PROJECT = env.subst("$PROJECT_DIR")  # noqa: F821
WEB_DIR = os.path.join(PROJECT, "web")
OUT = os.path.join(PROJECT, "include", "web_assets.h")


def read(name):
    with open(os.path.join(WEB_DIR, name), "r", encoding="utf-8") as fh:
        return fh.read()


def inline(html):
    """Replace the stylesheet link and script tag with their contents.

    Matched on the exact tags index.html uses rather than on anything general:
    a loose regex over HTML is a way to silently mangle a page, and there are
    two tags to handle.
    """
    css = read("app.css")
    js = read("app.js")

    html, n_css = re.subn(
        r'<link rel="stylesheet" href="app\.css">',
        lambda _: "<style>\n" + css + "\n</style>",
        html,
    )
    html, n_js = re.subn(
        r'<script src="app\.js"></script>',
        lambda _: "<script>\n" + js + "\n</script>",
        html,
    )
    if n_css != 1 or n_js != 1:
        raise RuntimeError(
            "web/index.html must reference app.css and app.js exactly once each "
            f"(found {n_css} and {n_js}) -- gen_web_assets.py inlines them by "
            "matching those tags literally"
        )
    return html


def emit(fh, symbol, data):
    # mtime=0 so an unchanged page produces an identical header, and a rebuild
    # that changed nothing does not show up as a changed image.
    blob = gzip.compress(data.encode("utf-8"), compresslevel=9, mtime=0)
    fh.write(f"\n// {symbol}: {len(data)} bytes of source, {len(blob)} gzipped\n")
    fh.write(f"static const size_t {symbol}_LEN = {len(blob)};\n")
    fh.write(f"static const uint8_t {symbol}[] = {{\n")
    for i in range(0, len(blob), 16):
        row = ", ".join(f"0x{b:02X}" for b in blob[i:i + 16])
        fh.write(f"    {row},\n")
    fh.write("};\n")
    return len(data), len(blob)


def build():
    index = inline(read("index.html"))
    manifest = read("manifest.webmanifest")

    out = io.StringIO()
    out.write("// GENERATED by scripts/gen_web_assets.py from web/ -- do not edit.\n")
    out.write("// Edit web/index.html, web/app.css, web/app.js instead.\n")
    out.write("#ifndef WEB_ASSETS_H\n#define WEB_ASSETS_H\n\n")
    out.write("#include <cstddef>\n#include <cstdint>\n")
    raw_i, gz_i = emit(out, "WEB_INDEX_GZ", index)
    raw_m, gz_m = emit(out, "WEB_MANIFEST_GZ", manifest)
    out.write("\n#endif  // WEB_ASSETS_H\n")
    text = out.getvalue()

    # Only write when something actually changed. This runs on every `pio run`,
    # and rewriting an identical header would leave the build looking as though
    # the front end had been touched.
    try:
        with open(OUT, "r", encoding="utf-8") as fh:
            if fh.read() == text:
                print(f"web assets: unchanged ({gz_i + gz_m} B of flash)")
                return
    except FileNotFoundError:
        pass

    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w", encoding="utf-8") as fh:
        fh.write(text)
    print(
        f"web assets: index {raw_i} -> {gz_i} B, manifest {raw_m} -> {gz_m} B "
        f"({gz_i + gz_m} B of flash)"
    )


build()
